---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image:  public.ecr.aws/nginx/nginx:1.27-alpine3.21-slim
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 128Mi
              cpu: 100m
      nodeSelector:
           eks.amazonaws.com/compute-type: auto
           kubernetes.io/arch : arm64                          

              
