apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: "${node_pool_name}"
spec:
  template:
    spec:
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: "${node_class_name}"
      taints:
      - key:    "health-graviton"
        effect: "NoSchedule"  
      requirements:
        - key: "kubernetes.io/arch"
          operator: In
          values: ["${instance_architecture}"] 
        - key: "eks.amazonaws.com/instance-category"
          operator: In
          values: ["${instance_category}"]
        - key: eks.amazonaws.com/instance-cpu
          operator: In
          values: ["${instance_cpu}"]
        - key: "eks.amazonaws.com/instance-hypervisor"
          operator: In
          values: ["nitro"]
        - key: "eks.amazonaws.com/instance-generation"
          operator: Gt
          values: ["2"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["${capacity_type}"]    
  limits:
    cpu: 1000
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 30s